### ISSUE TITLE
Not sudo

### ISSUE THREAD

**Issue by BjornB2** [robertklep/homebridge-klikaanklikuit#1]
Hi Robert, 

I am getting the following error in the error log:

```
Tue, 22 Mar 2016 11:38:48 GMT Accessory [Homebridge] Error setting Characteristic "On" to value true:  Command failed: kaku A 1 on
wiringPiSetup: Must be root. (Did you forget sudo?)
```

Am I doing something wrong with the kaku install? 

Thanks
Björn

**Comment by robertklep** [comment]
You need to make sure that the `kaku` executable is run with root privileges, either by running the `homebridge` executable as root (`sudo homebridge`) or by making the `kaku` executable _"suid root"_ (which I prefer myself):

```
$ sudo chown root:root /usr/local/bin/kaku
$ sudo chmod 4755 /usr/local/bin/kaku
```

(assuming that the executable is located in `/usr/local/bin`)

**Comment by BjornB2** [comment]
Thanks! That worked!
Now I only have to wait for the module to arrive :)

Björn

**Comment by robertklep** [comment]
Good luck! =D

**Comment by BjornB2** [comment]
Het werkt! Awesome!

https://www.instagram.com/p/BDTj-aSSs15/?taken-by=bjornheirman

Thanks voor je hulp en je homebridge plugin :)

Groet,
Björn

**Comment by robertklep** [comment]
Tof man! :+1:
