### ISSUE TITLE
Dim de acm-300 inbouw ontvanger

### ISSUE THREAD

**Issue by flipmoo** [robertklep/homebridge-klikaanklikuit#10]
Hallo,

Ik krijg mijn acm-300 inbouw ontvanger perfect aan en uit! Maar zou hem heel graag willen kunnen dimmen. Is dat mogelijk? Zo ja hoe? Dimmable true veranderd niks...

Alvast bedankt!

**Comment by robertklep** [comment]
Kun je even het relevante deel van `config.json` toevoegen?

**Comment by flipmoo** [comment]
{
      "name"     : "Test",
      "type"     : "Lightbulb",
      "dimmable" : true,
      "address"  : "K",
      "device"   : "1"
    }

**Comment by robertklep** [comment]
Waarschijnlijk genereert dat een warning bij het opstarten van Homebridge, omdat je een "oude" adressering gebruikt (met een letter ipv een cijfer voor `address`), en daar werkt dimming niet mee.

Omdat het een lerend device is (voor zover ik weet) kun je 'em een extra code laten leren, bv door gebruik te maken van de command line tool [in dit pakket](https://github.com/robertklep/node-kaku-rpi):
```
kaku PIN 12345 1 1
```

Daarmee zet je het adres "12345" (mag ook iets anders zijn), device nummer "1", op "aan". Zolang de ACM-300 in leermode staat zou ie die code moeten oppikken, en als je daarna de Homebridge config aanpast en opnieuw opstart zou het dimmen moeten werken:
```
{
  "name"     : "Test",
  "type"     : "Lightbulb",
  "dimmable" : true,
  "address"  : 12345,
  "device"   : 1
}
```

**Comment by flipmoo** [comment]
Ok ik ga dit zo gelijk proberen! Alvast super bedankt voor je snelle reactie.
Heb wel gelijk een aanvullende vraag. Kan ik uit die code halen welk kanaal het achteraf op de afstandbediening is? Zodat ik beide kan blijven gebruiken?

**Comment by robertklep** [comment]
De ACM-300 kan tot 6 codes leren, dus je kunt gewoon de oude code op de afstandsbediening blijven gebruiken.

**Comment by flipmoo** [comment]
Ik krijg hem weer keurig aan en uit geschakeld.... en me AB werkt idd ook nog.
Alleen werkt dimmen nog niet. (niet dmv de homekit knoppen... (is een schakelaar ipv dim schuif)) (en ook niet dmv siri.

Enig idee wat dit kan zijn? ik heb nu exact jou config staan zoals hierboven.

**Comment by flipmoo** [comment]
Ik kom er net achter dat het wel via de devices of insteon app te dimmen is...
maar homekit is wel me doel

**Comment by robertklep** [comment]
Vaak helpt het als je Homebridge stopt, `~/.homebridge/persist/` verwijderd, en Homebridge weer opnieuw opstart.

**Comment by flipmoo** [comment]
Ok dan, ga dat proberen! Zou ik jou een andere vraag mogen stellen? Ik gebruik naast Kaku accessoires ook 1 om me marantz versterker aan en uit te schakelen. Los van elkaar werken ze goed. Maar ik krijg ze niet samen in de json file. Kun je me eventueel uitleggen wat ik verkeer doe?

Ziet er nu zo uit:


{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:22:3D:E3:CE:30",
		"port": 51826,
		"pin": "111-11-111"
	},


	"platforms": [{
			"platform": "Nest",
			"token": "xxx",
			"clientId": "xxx",
			"clientSecret": "xxx",
			"code": "xxx",
			"username": "XXX@xxx.com",
			"password": "XXX"

		},

		{
			"platform": "KlikAanKlikUit",
			"driver": {
			"type": "rpi",
				"pin": 11
			},
			"accessories": [{
				"name": "Bed",
				"type": "Switch",
				"address": "B",
				"device": "1"
			},
			{
				"name": "Sem",
				"type": "Outlet",
				"address": "A",
				"device": "1"
			},{
				"name": "Subwoofer",
				"type": "Outlet",
				"address": "C",
				"device": "1"
			},{
				"name": "Test",
				"type": "Lightbulb",
				"dimmable": true,
				"address": 12345,
				"device": "1"
					}]
			}]

	"accessories" [{
		"accessory": "DenonMarantzAVR",
		"name": "Versterker",
		"ip": "192.168.2.5",
		"defaultInput": "TV",
		"defaultVolume": 35,
		"minVolume": 10,
		"maxVolume": 75
	}]
}

**Comment by robertklep** [comment]
Er mist een comma na de `}]` die bij `"platforms"` hoort, en na `"accessories"` moet een dubbele punt komen.

Zo:
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "111-11-111"
  },
  "platforms": [
    {
      "platform": "Nest",
      "token": "xxx",
      "clientId": "xxx",
      "clientSecret": "xxx",
      "code": "xxx",
      "username": "XXX@xxx.com",
      "password": "XXX"
    },
    {
      "platform": "KlikAanKlikUit",
      "driver": {
        "type": "rpi",
        "pin": 11
      },
      "accessories": [
        {
          "name": "Bed",
          "type": "Switch",
          "address": "B",
          "device": "1"
        },
        {
          "name": "Sem",
          "type": "Outlet",
          "address": "A",
          "device": "1"
        },
        {
          "name": "Subwoofer",
          "type": "Outlet",
          "address": "C",
          "device": "1"
        },
        {
          "name": "Test",
          "type": "Lightbulb",
          "dimmable": true,
          "address": 12345,
          "device": "1"
        }
      ]
    }
  ],
  "accessories": [
    {
      "accessory": "DenonMarantzAVR",
      "name": "Versterker",
      "ip": "192.168.2.5",
      "defaultInput": "TV",
      "defaultVolume": 35,
      "minVolume": 10,
      "maxVolume": 75
    }
  ]
}
```

Via een online editor als [deze](http://www.cleancss.com/json-editor/) kun je dat soort problemen vaak wel oplossen :D

**Comment by flipmoo** [comment]
Helemaal super!! Werkt als een tierelier! :)
Aangezien je me zo goed helpt kan ik het niet laten om nog een vraag te stellen.
Ik heb ook nog een soort ontvanger uit china wat met een soort auto AB werkt. Nu weet ik dat die ook op 433mhz werkt. Zou dit ook eenvoudig via homebridge te sturen zijn?

**Comment by robertklep** [comment]
Meestal kun je die wel werkend krijgen, maar het probleem is dat je precies moet weten wat voor soort code die AB opstuurt (en vervolgens moet je daar de juiste Homebridge plugin bij vinden).

Om die code te vinden moet je iets bouwen met een 433Mhz ontvanger, en een Arduino (o.i.d.) om die ontvanger uit te lezen. Een instructable kun je [hier](http://www.instructables.com/id/Decoding-and-sending-433MHz-RF-codes-with-Arduino-/) vinden.

**Comment by flipmoo** [comment]
Leuk om eens een keer te gaan proberen.
Ik heb wel nog een andere vraag. Nadat gister alles goed werkte had ik besloten om eens ene clean install te doen van de Pi. Want had nogal wat vervuiling op gelopen door alle trail en errors... Maar je zal net zien dat ik het nu niet meer an de praat krijg. Wete jij nog een goede handleiding voor het aansturen van de 433mhz tansmitter? Want de link in jou tut. werkt niet.

**Comment by robertklep** [comment]
Probeer deze link eens: http://weejewel.tweakblogs.net/blog/8665/lampen-schakelen-met-een-raspberry-pi

Ik denk dat je na het aansluiten van de hardware al voldoende hebt om het werkend te krijgen, wellicht (maar dat weet ik niet zeker) dat je WiringPi ook moet installeren, maar de daar genoemde `lights.zip` is zeker niet nodig.

**Comment by flipmoo** [comment]
ik loop dan tegen het volgende aan:

pi@raspberrypi:~ $ git clone git://git.drogon.net/wiringPi
Cloning into 'wiringPi'...
remote: Counting objects: 1059, done.
remote: Compressing objects: 100% (877/877), done.
remote: Total 1059 (delta 752), reused 212 (delta 142)
Receiving objects: 100% (1059/1059), 329.48 KiB | 0 bytes/s, done.
Resolving deltas: 100% (752/752), done.
Checking connectivity... done.
pi@raspberrypi:~ $ cd wiringPi
pi@raspberrypi:~/wiringPi $ 
pi@raspberrypi:~/wiringPi $ git pull origin
Already up-to-date.
pi@raspberrypi:~/wiringPi $ cd wiringPi
pi@raspberrypi:~/wiringPi/wiringPi $ ./build
-bash: ./build: No such file or directory

**Comment by flipmoo** [comment]
Gevolg is (denk ik) dat ik nu bij starten van de hombridge dit krijg:

events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE :::51826
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at Server._listen2 (net.js:1259:14)
    at listen (net.js:1295:10)
    at Server.listen (net.js:1391:5)
    at EventedHTTPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/eventedhttp.js:60:19)
    at HAPServer.listen (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/HAPServer.js:158:20)
    at Bridge.Accessory.publish (/usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:496:16)
    at Server._publish (/usr/lib/node_modules/homebridge/lib/server.js:114:16)
    at Server.<anonymous> (/usr/lib/node_modules/homebridge/lib/server.js:372:14)
    at /usr/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/util/once.js:15:19
    at /usr/lib/node_modules/homebridge-nest/index.js:155:6

**Comment by robertklep** [comment]
Zo te zien draai je Raspbian? Dan kun je beter de package manager gebruiken voor het installeren van WiringPi:
```
sudo apt-get install wiringpi
```

En die `EADDRINUSE` betekent dat Homebridge al draait.

**Comment by flipmoo** [comment]
Ok, KaKu werkt weer... er zat schijnbar iets in de weg van me aansturen voor de versterker... die eerst wel werkte.
Maar nu een stroring op alles geeft.
Geen idee waarom alleen

**Comment by flipmoo** [comment]
Was een probleem met een ip adres wat anders was....
Nu helemaal opgelost!!
Mag ik je onwijs bedanken voor je hulp?!

**Comment by robertklep** [comment]
Graag gedaan hoor!
