### ISSUE TITLE
Kodi Vraag

### ISSUE THREAD

**Issue by flipmoo** [robertklep/homebridge-klikaanklikuit#11]
Hoi Robert,

Aangezien jij op dit moment de enige bent die ik "ken", die verstand heeft van al dit moois.
Wil ik je graag wat vragen. 
Alleen ben ik bang dat ik nu dit element van githuib vervuil... omdat ik niet goed weet of dit de juiste plek is om zoiets te vragen. (kon geen PB functie vinden).
Daarbij weet ik niet of je me kan en wil helpen. Maar ik ben opzoek naar ene oplossing om Kodi (die draait op me raspberry) te starten en stoppen dmv homebridge.
Doel is om een scene te kunnen maken. Waar mee me versterker en sub aangaan (werken al in homebrdige) Licht dimt (werkt ook) tv aan gaat (zou dmv CEC door HDMi moeten gaan) en Kodi start. (werkt nog niet :) ) EN uiteraard alles andersom door de scene weer uit te zetten.

Hoop dat je me kan en wil helpen.

Alvast bedankt.

**Comment by robertklep** [comment]
Hee Koen, stuur anders ff een e-mail naar me, robert AT klep DOT name (AT en DOT vervangen door apestaartje en punt :D
