### ISSUE TITLE
Does anyone know whether this works with a USB 433 mhz transceiver?

### ISSUE THREAD

**Issue by RoachMech** [robertklep/homebridge-klikaanklikuit#12]
And what pin number should be entered in the config of the platform?

**Comment by robertklep** [comment]
For now it only works with transmitters connected to the GPIO pins on the RPi.

FWIW, these transmitters are [very cheap](https://www.aliexpress.com/item/RF-wireless-receiver-module-transmitter-module-board-Ordinary-super-regeneration-315-433MHZ-DC5V-ASK-OOK-5pair/32321094186.html), and it's not very difficult to hook them up.

**Comment by RoachMech** [comment]
Thanks @robertklep for the quick amd clear response!
