### ISSUE TITLE
get codes of wall switch transmitters

### ISSUE THREAD

**Issue by poudenes** [robertklep/homebridge-klikaanklikuit#14]
Hi There all,

Love this plugin, work well !!!
I also have switched to turn lights on manual. I want to get those codes to use them in homebridge.

Also still find out to get a plugin that only receives codes in homebridge so homebridge will turn on a switch. When i have this, i can config homebridge with this wall switch codes, and send a turn on signal to my lights by homebridge.  i get then next example idea:

Manual hit switch1, then homebridge receive the code, homebridge send by a rule a light bulb on.
Manual hit switch1, then homebridge receive the code, homebridge send by a rule a light bulb off.

etc with switch2, 3, 4, ....

Then i can turn on lights using manual switch and homebridge. And status of lamp will always be correct in homekit, eve, of whatever you use.

**Comment by marathonworks** [comment]
Agreed! I would also be interested in catching RF codes en sending different ones to the bulbs/switches. That way the homebridge state would always be up to date (unless there is a power outage).

I have only used the RF sniffer tool from https://github.com/ninjablocks/433Utils/tree/master/RPi_utils to catch remote commands. Unfortunately I am not advanced enough to implement this in code..

@robertklep what do you think, is this possible? :-)

**Comment by robertklep** [comment]
There's already a Homebridge plugin that seems to be able to support this: [`homebridge-rfbuttons`](https://www.npmjs.com/package/homebridge-rfbuttons).

It's actually something that I should look into myself, I have a few cheap 433Mhz remotes ("key clone"-types like [this one](https://www.aliexpress.com/item/New-4-Channel-Remote-Control-433-MHz-Cloning-Duplicator-Opener-Copy-Controller-Learning-Code-Garage-Door/32673095696.html)) that I can't use for anything else (they don't accept KaKu codes, for instance) that I may be able to put to use.
