### ISSUE TITLE
config.json

### ISSUE THREAD

**Issue by pjansen75** [robertklep/homebridge-klikaanklikuit#16]
Hello Robert,
I am really desperated about my config file.
I don't get it to work. I tried a lot, but it will not have any result.
The code that you published on the site is not working for me, homebridge reads an error in the file.
This is what I have now:

{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:21:3E:E4:DE:33",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "KlikAanKlikUit",
		"driver": "KaKu",
		"type": "kaku-rpi",
		"pin": 11
	}],
	"accessories": [{
		"name": "Spotjes zolderkamer",
		"type": "Lightbulb",
		"dimmable": false,
		"address": "M",
		"device": "1"
	}]
}

Please, can you help me to configure it as a working configuration?
Thanks in advance.

Regards, Pieter

**Comment by robertklep** [comment]
Hi @pjansen75!

Try this:
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:21:3E:E4:DE:33",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "KlikAanKlikUit",
      "driver": {
        "type": "rpi",
        "pin": 11
      },
      "accessories": [
        {
          "name": "Spotjes zolderkamer",
          "type": "Lightbulb",
          "dimmable": false,
          "address": "M",
          "device": 1
        }
      ]
    }
  ]
}
```

**Comment by pjansen75** [comment]
Yes, it is loading now. And... working. :-)
Thank you

**Comment by robertklep** [comment]
Nice, have fun!
