### ISSUE TITLE
Crashes when launching as service

### ISSUE THREAD

**Issue by greensouth** [robertklep/homebridge-klikaanklikuit#17]
When I run homebridge as a normal application, works fine, but when I add the platform and launch via 

> sudo systemctl start homebridge

, it just crashes.

What could be happening here?

**Comment by robertklep** [comment]
No idea what's happening. What does `sudo systemctl status homebridge` show?

**Comment by greensouth** [comment]
Sep  9 19:52:32 raspberrypi homebridge[24833]: [2017-9-9 19:52:32] [homebridge-klikaanklikuit] using driver 'rpi'
Sep  9 19:52:32 raspberrypi homebridge[24833]: bcm2835_init: Unable to open /dev/gpiomem: Permission denied
Sep  9 19:52:32 raspberrypi homebridge[24833]: /usr/lib/node_modules/homebridge-klikaanklikuit/index.js:26
Sep  9 19:52:32 raspberrypi homebridge[24833]: throw Error(`Unable to load driver '${ driver.type }': ${ e.message }`);
Sep  9 19:52:32 raspberrypi homebridge[24833]: ^
Sep  9 19:52:32 raspberrypi homebridge[24833]: Error: Unable to load driver 'rpi': Could not initialize bcm2835 GPIO library
Sep  9 19:52:32 raspberrypi homebridge[24833]: at new KaKuPlatform (/usr/lib/node_modules/homebridge-klikaanklikuit/index.js:26:13)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:294:32)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:80:36)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Module._compile (module.js:571:32)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Object.Module._extensions..js (module.js:580:10)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Module.load (module.js:488:32)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at tryModuleLoad (module.js:447:12)
Sep  9 19:52:32 raspberrypi homebridge[24833]: at Function.Module._load (module.js:439:3)

**Comment by robertklep** [comment]
```
bcm2835_init: Unable to open /dev/gpiomem: Permission denied
```

That suggests that the Homebridge systemctl service isn't being run as a user that has access to `/dev/gpiomem` (also explained here: https://github.com/jperkin/node-rpio#install)

You can find out with which username the Homebridge service is being started as like this:
```
systemctl show homebridge | grep User=
```

And add that user to the group `gpio`:
```
sudo addgroup USER gpio
```
(replace `USER` by the correct username)

**Comment by greensouth** [comment]
Thank you so much dude! That is what happens when you are a noob at unix... :/
No problems launching as a service now, and it's supposed to work, but it still doesn't. 

Kinda curious, I launch kaku command line (kaku 12 12 9 1) (pin 12, id 12, unit 9, turn on) and works, but when triggering from homebridge, I see it's sending the same code using pilight-receive, but doesn't turn or off anything.

It's weird, what i'm doing wrong? it's like a day or so fighting with this :( 

Forget about it, had to make the sockets re-learn the codes sent via homebridge. Wow!! That's weird and amazing at the same time. Thanks for your help and your amazing work!

**Comment by robertklep** [comment]
Glad to be of help! Enjoy automating your home 😃
