### ISSUE TITLE
Doesn't work with some new KaKu receivers

### ISSUE THREAD

**Issue by Monkeystation** [robertklep/homebridge-klikaanklikuit#2]
It appears it doesn't work with the ALED-2709. This is a kaku led-lamp. The lamp also does not pair with the old YCT-102 remote, but does pair with a newer wall switch.
The plug-in works perfectly with all my other old and newer receivers, so it seems the ALED is using some new kind of protocol / handshake.

**Comment by robertklep** [comment]
I only have (really) old receivers, but I know that the protocols have changed considerably. However, because I don't have recent receivers I won't be able to test against those, so for now, this plugin will only support older receivers (I'll update the README to reflect that).

**Comment by robertklep** [comment]
Okay, I ordered a few items, including the ALED-2009 (which, I assume, will be talking the same protocol as the 2709). With a bit of luck, I'll be able to implement the protocol.

**Comment by Monkeystation** [comment]
Hi Robert, spend all weekend playing around with the code and got it all working! I've also uploaded my code here in Git and on NPM. Used basically your files as a starting point (this is all new for me, so thanks!). You can find it here: https://github.com/Monkeystation/homebridge-remote-transmitter

**Comment by robertklep** [comment]
Nice! Once I get my new gear (hopefully tomorrow) I plan on extending my plugin to allow both old and new-style devices, and also add brightness control. I might borrow your `NewRemoteTransmitter.js` if you're okay with that :D

**Comment by Monkeystation** [comment]
That would be a perfect solution! Surely you can use the NewRemoteTransmitter.js, I couldn't have done it without your code.

**Comment by robertklep** [comment]
Just pushed `homebridge-klikaanklikuit@1.0.0` (new name, minus the hyphen, so new versioning; the old package has been marked _deprecated_) that supports new-style receivers and dimming (fixes #3 as well).
