### ISSUE TITLE
Homebridge will not start with homebridge-klikaanklikuit plugin

### ISSUE THREAD

**Issue by ghost** [robertklep/homebridge-klikaanklikuit#22]
I had to reconfigure my RPI3 with homebridge after it crashed.
I have installed Rasbian Stretch, Node v8.9.4. 
After installing the klikaanklikuit plugin end putting my working JSON file back i get the following:
[2018-2-7 12:33:52] [KlikAanKlikUit] Initializing KlikAanKlikUit platform...
/usr/lib/node_modules/homebridge-klikaanklikuit/index.js:26
      throw Error(`Unable to load driver '${ driver.type }': ${ e.message }`);
      ^

Error: Unable to load driver 'rpi': Could not locate the bindings file. Tried:
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/Release/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/out/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/Debug/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/out/Release/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/Release/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/default/rpio.node
 → /usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/compiled/8.9.4/linux/arm/rpio.node
    at new KaKuPlatform (/usr/lib/node_modules/homebridge-klikaanklikuit/index.js:26:13)
    at Server._loadPlatforms (/usr/lib/node_modules/homebridge/lib/server.js:304:32)
    at Server.run (/usr/lib/node_modules/homebridge/lib/server.js:85:36)
    at module.exports (/usr/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Function.Module.runMain (module.js:684:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3

**Comment by robertklep** [comment]
This seems to suggest that the plugin wasn't fully, or properly, installed.

Can you post the output generated during the installation as well? You can use something like this:
```
npm i homebridge-klikaanklikuit -g 2>&1 | tee output.log
```

**Comment by ghost** [comment]
+ homebridge-klikaanklikuit@1.2.0
updated 1 package in 2.479s

**Comment by robertklep** [comment]
Hmm that's not very useful :(

Try this (added `-f`, or _force reinstall_):
```
npm i homebridge-klikaanklikuit -g -f 2>&1 | tee output.log

**Comment by ghost** [comment]
npm WARN using --force I sure hope you know what you are doing.
+ homebridge-klikaanklikuit@1.2.0
updated 1 package in 2.448s

**Comment by robertklep** [comment]
Next try:
```
npm i homebridge-klikaanklikuit -g -f --verbose 2>&1 | tee output.log
```

I need a full installation log.

**Comment by ghost** [comment]
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'i',
npm verb cli   'homebridge-klikaanklikuit',
npm verb cli   '-g',
npm verb cli   '-f',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm WARN using --force I sure hope you know what you are doing.
npm verb npm-session 0dd1275067211047
npm http fetch GET 304 https://registry.npmjs.org/homebridge-klikaanklikuit 421ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/kaku-rpi 89ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/debug 98ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rpio 168ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 67ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 119ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 118ms (from cache)
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm info lifecycle homebridge-klikaanklikuit@1.2.0~preuninstall: homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~uninstall: homebridge-klikaanklikuit@1.2.0
npm verb unbuild rmStuff homebridge-klikaanklikuit@1.2.0 from /usr/lib/node_modules
npm info lifecycle homebridge-klikaanklikuit@1.2.0~postuninstall: homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~preinstall: homebridge-klikaanklikuit@1.2.0
npm info linkStuff homebridge-klikaanklikuit@1.2.0
npm verb linkBins homebridge-klikaanklikuit@1.2.0
npm verb linkMans homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~install: homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~postinstall: homebridge-klikaanklikuit@1.2.0
npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
+ homebridge-klikaanklikuit@1.2.0
updated 1 package in 2.644s
npm verb exit [ 0, true ]
npm info ok

**Comment by robertklep** [comment]
Thanks, that looks okay.

Try reinstalling the `rpio` module. It's probably easiest to do that in a temporary directory:
```
$ cd /tmp
$ npm i rpio
$ node -r rpio -e ''
```

That should not throw any errors.

**Comment by ghost** [comment]
pi@raspberrypi:/tmp $ node -r rpio -e ''
/tmp/node_modules/bindings/bindings.js:96
  throw err
  ^

Error: Could not locate the bindings file. Tried:
 → /tmp/node_modules/rpio/build/rpio.node
 → /tmp/node_modules/rpio/build/Debug/rpio.node
 → /tmp/node_modules/rpio/build/Release/rpio.node
 → /tmp/node_modules/rpio/out/Debug/rpio.node
 → /tmp/node_modules/rpio/Debug/rpio.node
 → /tmp/node_modules/rpio/out/Release/rpio.node
 → /tmp/node_modules/rpio/Release/rpio.node
 → /tmp/node_modules/rpio/build/default/rpio.node
 → /tmp/node_modules/rpio/compiled/8.9.4/linux/arm/rpio.node
    at bindings (/tmp/node_modules/bindings/bindings.js:93:9)
    at Object.<anonymous> (/tmp/node_modules/rpio/lib/rpio.js:17:34)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
    at Module.require (module.js:587:17)
    at Function.Module._preloadModules (module.js:744:12)
    at preloadModules (bootstrap_node.js:471:38)

**Comment by ghost** [comment]
pi@raspberrypi:/tmp $ npm i rpio
npm WARN checkPermissions Missing write access to /tmp/node_modules/rpio
npm WARN enoent ENOENT: no such file or directory, open '/tmp/package.json'
npm WARN tmp No description
npm WARN tmp No repository field.
npm WARN tmp No README data
npm WARN tmp No license field.

npm ERR! path /tmp/node_modules/rpio
npm ERR! code EACCES
npm ERR! errno -13
npm ERR! syscall access
npm ERR! Error: EACCES: permission denied, access '/tmp/node_modules/rpio'
npm ERR!  { Error: EACCES: permission denied, access '/tmp/node_modules/rpio'
npm ERR!   stack: 'Error: EACCES: permission denied, access \'/tmp/node_modules/rpio\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/tmp/node_modules/rpio' }
npm ERR! 
npm ERR! Please try running this command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2018-02-07T13_20_34_739Z-debug.log

**Comment by ghost** [comment]
Changes permissions for the rpio folder.
Now it ran ok.
but Hombridge is still not starting

Same massage as previously.

**Comment by robertklep** [comment]
This was only in a temporary directory, now try installing it globally:
```
npm i rpio -g
```

My guess is that it will run into similar issues (incorrect permissions).

**Comment by ghost** [comment]
+ rpio@0.9.20
updated 1 package in 14.639s

**Comment by ghost** [comment]
Homebridge still not starting, same message

**Comment by robertklep** [comment]
Did you try running `node -r rpio -e ''` after installing it globally? Preferably _not_ from the `/tmp` directory (because in that case, Node will find the version installed there, which we know will work).

**Comment by ghost** [comment]
pi@raspberrypi:/ $ npm i rpio -g

> rpio@0.9.20 install /usr/lib/node_modules/rpio
> node-gyp rebuild

make: Entering directory '/usr/lib/node_modules/rpio/build'
  CC(target) Release/obj.target/rpio/src/bcm2835.o
  CXX(target) Release/obj.target/rpio/src/rpio.o
  SOLINK_MODULE(target) Release/obj.target/rpio.node
  COPY Release/rpio.node
make: Leaving directory '/usr/lib/node_modules/rpio/build'
+ rpio@0.9.20
updated 1 package in 12.884s
pi@raspberrypi:/ $ node -r rpio -e ''
module.js:540
    throw err;
    ^

Error: Cannot find module 'rpio'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at Function.Module._preloadModules (module.js:744:12)
    at preloadModules (bootstrap_node.js:471:38)
    at startup (bootstrap_node.js:158:9)
    at bootstrap_node.js:608:3
pi@raspberrypi:/ $

**Comment by robertklep** [comment]
I think the best thing right now it so just remove `homebridge-klikaanklikuit` manually:
```
sudo rm -fr /usr/lib/node_modules/homebridge-klikaanklikuit
```

And re-install it again (making sure there aren't any permission issues popping up).

**Comment by ghost** [comment]
@raspberrypi:/ $ sudo npm i homebridge-klikaanklikuit -g -f --verbose 2>&1 | tee output.log
tee: output.log: Permission denied
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node',
npm verb cli   '/usr/bin/npm',
npm verb cli   'i',
npm verb cli   'homebridge-klikaanklikuit',
npm verb cli   '-g',
npm verb cli   '-f',
npm verb cli   '--verbose' ]
npm info using npm@5.6.0
npm info using node@v8.9.4
npm WARN using --force I sure hope you know what you are doing.
npm verb npm-session 3957bdce9bdb5fb4
npm http fetch GET 304 https://registry.npmjs.org/homebridge-klikaanklikuit 422ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/kaku-rpi 220ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/debug 111ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/rpio 188ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/ms 127ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/bindings 108ms (from cache)
npm http fetch GET 304 https://registry.npmjs.org/nan 116ms (from cache)
npm verb correctMkdir /root/.npm/_locks correctMkdir not in flight; initializing
npm verb lock using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
npm info lifecycle homebridge-klikaanklikuit@1.2.0~preuninstall: homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~uninstall: homebridge-klikaanklikuit@1.2.0
npm verb unbuild rmStuff homebridge-klikaanklikuit@1.2.0 from /usr/lib/node_modules
npm info lifecycle homebridge-klikaanklikuit@1.2.0~postuninstall: homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~preinstall: homebridge-klikaanklikuit@1.2.0
npm info linkStuff homebridge-klikaanklikuit@1.2.0
npm verb linkBins homebridge-klikaanklikuit@1.2.0
npm verb linkMans homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~install: homebridge-klikaanklikuit@1.2.0
npm info lifecycle homebridge-klikaanklikuit@1.2.0~postinstall: homebridge-klikaanklikuit@1.2.0
npm verb unlock done using /root/.npm/_locks/staging-a072192f34a17023.lock for /usr/lib/node_modules/.staging
+ homebridge-klikaanklikuit@1.2.0
updated 1 package in 2.781s
npm verb exit [ 0, true ]
npm info ok

**Comment by ghost** [comment]
SOLVED
Flashed the SD and reinstalled homebridge using Node 6.x
Now the klikaanklikuit plugin works again.

Thanks for the quick responses.

**Comment by robertklep** [comment]
Thanks for the update! Perhaps Node 8.x is the issue, I have to look into that.
