### ISSUE TITLE
Can't get it to work with APA2-2300R Outlets

### ISSUE THREAD

**Issue by karstenm** [robertklep/homebridge-klikaanklikuit#23]
Hello! 

I am trying to get the plugin to work with the APA2-2300R outlets, but they just won't receive anything.

I have tested the transmitter with an LED to see if it is connected to the right GPIO and that functions very well. When I press the accessory in the home app, the LED blinks. 

When I put the APA2-2300R outlet in learning mode by plugging it into the wall, nothing happens. I have tried several codes and I have tried to sent the signal via the kaku-rpi module, but nothing works.

I am starting to think that the product is not suitable to connect with the plugin. How can I use these outlets with the homebridge plugin. 

It would be great to get some help, it's so frustrating to see nothing happen:)

**Comment by robertklep** [comment]
I don't have these outlets, so can only offer some generic answers.

It looks like these outlets can only be paired with at most 3 transmitters, so perhaps all slots are filled? You could try and see if resetting the device makes it work.

I _would_ recommend using the `kaku` CLI tool to learn a new code into the device. This tool supports "old style" and "new style" KaKu devices. Perhaps your outlets only accept "old style" codes (where the _ADDRESS_ argument for the `kaku` tool should be a letter, A to D usually).

**Comment by karstenm** [comment]
Thanks you're a legend. The memory was indeed full. I have cleared the memory and everything works like a charm now. Awesome!

**Comment by robertklep** [comment]
Great, good to hear you got it working 😄
