### ISSUE TITLE
Nodejs 8 & klikaanklikuit 

### ISSUE THREAD

**Issue by hugo-leij** [robertklep/homebridge-klikaanklikuit#27]
Hi,

I run into the following error:
`
/usr/local/lib/node_modules/homebridge-klikaanklikuit/index.js:26
      throw Error(Unable to load driver '${ driver.type }': ${ e.message });
      ^
`
This problem has also been reported in the following tickets: https://github.com/robertklep/homebridge-klikaanklikuit/issues/25 , https://github.com/robertklep/homebridge-klikaanklikuit/issues/22

In the meantime I have done a few new installations (several times) and with NodeJS 4 everything works. The problem is that I need NodeJS 8 for my Nest.

**Comment by hugo-leij** [comment]
Fixed the issue :-)

pi@raspberrypi:~ $ cd /usr/local/lib/node_modules/homebridge-klikaanklikuit/node_modules/kaku-rpi/
pi@raspberrypi:/usr/local/lib/node_modules/homebridge-klikaanklikuit/node_modules/kaku-rpi $ sudo npm rebuild --unsafe-perm

**Comment by robertklep** [comment]
Cool, thanks for letting me know how to fix this, you're not the only one running into this problem so now I can share a solution ;)
