### ISSUE TITLE
Does not control brightness capabilities

### ISSUE THREAD

**Issue by Monkeystation** [robertklep/homebridge-klikaanklikuit#3]
I'm not sure if this would be possible to implement but many KaKu devices have dimming capabilities. With the basic remote this works by turning on the lamp/switch, press on again to start cycling through from light to dark and vice versa, and confirm by pressing on again.
Apparently the Internet Control Systems can also adjust the brightness directly to a given percentage. This could perhaps work with the brightness slider in Homebridge?

**Comment by robertklep** [comment]
I should go and buy some newer KaKu stuff, I guess ;D

**Comment by Monkeystation** [comment]
Haha yes! The brightness control is a really nice feature. I've embedded some dimmer switches into my wall sockets which works nicely. I've also added a brightness control to your homebridge plugin which at least allows me to send several "on" commands to the receiver, making it possible to use the basic dimming capabilities. Though it's a bit of a hack and definitely not perfect. 
I'm pretty new to the HomeKit / Homebridge world and I was wondering if it is possible to display separate on-off switches in the Apple Home app instead of the current toggle switch? This way you could also control the dimming the same way as the KaKu remote does. Even better off course would be to get the brightness control actually working :)

**Comment by robertklep** [comment]
> I'm pretty new to the HomeKit / Homebridge world and I was wondering if it is possible to display separate on-off switches in the Apple Home app instead of the current toggle switch?

Right now, the default Homebridge service that's being used is _"Outlet"_.

You can configure the service in the configuration file. An example is shown [in the README](https://github.com/robertklep/homebridge-klikaan-klikuit#configuration), where the first device is configured as a _"Lightbulb"_. However, the only characteristic that's supported at the moment is _On_ (to toggle the lightbulb/switch on/off; lightbulbs also have other characteristics that may be worth implementing, but to test those I'm really going to need some actual devices).

Others you could try are [_"Switch"_](https://github.com/KhaosT/HAP-NodeJS/blob/07382139ef63ab3c4004263e9b24c6fe670115c7/lib/gen/HomeKitTypes.js#L2758) <s>or [_"StatelessProgrammableSwitch"_](https://github.com/KhaosT/HAP-NodeJS/blob/07382139ef63ab3c4004263e9b24c6fe670115c7/lib/gen/HomeKitTypes.js#L2740) (I have no idea what the difference between those two is, nor if they will be presented any differently from the default _"Outlet"_)</s> The _"StatelessProgrammableSwitch"_ uses a different characteristic than _Outlet_ and _Switch_ so won't work.
