### ISSUE TITLE
Broken URL 

### ISSUE THREAD

**Issue by rcuijpers** [robertklep/homebridge-klikaanklikuit#31]
Hi Robert,

De link voor de hardware werkt niet meer. Ik heb nog 3 KlikAanKlikUit (rotary switch) liggen, lijkt me leuk om deze met de Homebrigde aan te kunnen sturen. 

Echter weet ik nu niet welke ik moet bestellen.

Alvast bedankt voor je advies! 
Roel

///////////////////////

Hi Robert,

The URL for the hardware is not working. Maybe you can advise me on what to buy or replace the link?

Thanks a bunch,

Roel

**Comment by robertklep** [comment]
Hey Roel,

Check this page: https://domoticproject.com/controlling-433-mhz-remote-raspberry-pi/#433MHz_modules

By default, `homebridge-klikaanklikuit` uses pin 11 (GPIO17) for the transmitter.

I will update the README file.
