### ISSUE TITLE
Unable to load driver

### ISSUE THREAD

**Issue by rcuijpers** [robertklep/homebridge-klikaanklikuit#36]
Hi Robert, 
I've been using your plugin for a year now and I absolutely love it. Today i've updated my raspberry's node version and homebridge gives me an error on the RPI driver build.

` [KlikAanKlikUit] Initializing KlikAanKlikUit platform...
Nov 23 11:17:37 raspberrypi homebridge[2530]: [11/23/2020, 11:17:37 AM] Error: Unable to load driver 'rpi': The module '/usr/lib/node_modules/homebridge-klikaanklikuit/node_modules/rpio/build/Release/rpio.node'
Nov 23 11:17:37 raspberrypi homebridge[2530]: was compiled against a different Node.js version using
Nov 23 11:17:37 raspberrypi homebridge[2530]: NODE_MODULE_VERSION 72. This version of Node.js requires
Nov 23 11:17:37 raspberrypi homebridge[2530]: NODE_MODULE_VERSION 88. Please try re-compiling or re-installing
Nov 23 11:17:37 raspberrypi homebridge[2530]: the module (for instance, using `npm rebuild` or `npm install`).
`

Is this something you can help me with or maybe send me on my way with a link or tutorial on how to fix this? 
Thanks a million!

**Comment by robertklep** [comment]
You need to reinstall the plugin with the new Node.js version. You can use the [installation instructions](https://github.com/robertklep/homebridge-klikaanklikuit#installation) to reinstall it.
