### ISSUE TITLE
Not working with Homebridge

### ISSUE THREAD

**Issue by ghost** [robertklep/homebridge-klikaanklikuit#6]
Hi Robert,

First of all thank you very much for your amazing work on the KAKU and Homebridge.
However, I get stuck in the installing process.

I managed to get the KAKU working with my RPI, in cooperation with wiringPi (with help of the Dutch blog) I tested it, and I can control the lights with a simple code. After that I installed Homebridge, and that was working fine also (it started, and my iPhone saw the Homebridge) 

At last I installed your plugin from NPM and everything went fine. But the first issues I get is with the config.json. It is getting a lot of errors. Maybe you can send the one you use? 

After 1/2 hours I managed to get the config.json working, but not in a correct way I think. When I want to start Homebridge again, I get an error: "TypeError: Cannot read property "indexOf" of undefined.

Also I think another error is with this: /usr/local/lib/node_modules/homebridge/lib/api.js:104

Do you know something what caused this error?
Thanks!

**Comment by robertklep** [comment]
Feel free to post your config here, and I'll take a look at it :)

**Comment by ghost** [comment]
HI Robert,

Thank you for your quick reaction!
This is my code:

{
    "bridge": {
        "name": "Homebridge",
        "username": "CD:22:3D:E3:CE:30",
        "port": 51826,
        "pin": "031-45-156"
    },

```
"description": "Your description.",

"platforms": [{
    "platform": "KlikAanKlikUit",
    "driver": {
        "type": "rpi",
        "pin": 8
    }
}],
"accessories": [{
        "name": "Lamp 1",
        "type": "Lightbulb",
        "dimmable": false,
        "address": "A",
        "device": "1"
    }, {
        "name": "Lamp 2",
        "type": "Lightbulb",
        "dimmable": false,
        "address": "B",
        "device": "1"
    },
        "name": "Lamp 3",
        "type": "Lightbulb",
        "dimmable": false,
        "address": "C",
        "device": "1"

}]
```

}

**Comment by robertklep** [comment]
@RFGRTHR ah okay, the `accessories` need to be _inside_ the platform object, like this:

```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CD:22:3D:E3:CE:30",
    "port": 51826,
    "pin": "031-45-156"
  },
  "description": "Your description.",
  "platforms": [
    {
      "platform": "KlikAanKlikUit",
      "driver": {
        "type": "rpi",
        "pin": 8
      },
      "accessories": [
        {
          "name": "Lamp 1",
          "type": "Lightbulb",
          "dimmable": false,
          "address": "A",
          "device": "1"
        },
        {
          "name": "Lamp 2",
          "type": "Lightbulb",
          "dimmable": false,
          "address": "B",
          "device": "1"
        },
        {
          "name": "Lamp 3",
          "type": "Lightbulb",
          "dimmable": false,
          "address": "C",
          "device": "1"
        }
      ]
    }
  ]
}
```

**Comment by ghost** [comment]
Robert,

You are a hero! It all works perfectly now!
Thank you very much for your great job, and quick reply's!

Have a nice day.

KR
Ruben

**Comment by robertklep** [comment]
Good to hear! Have fun :D
