### ISSUE TITLE
not possible to use an api or something ?

### ISSUE THREAD

**Issue by gielk** [robertklep/homebridge-klikaanklikuit#7]
i don't have a raspberry pi why not use api or something ?

**Comment by robertklep** [comment]
Where would that API be running?

**Comment by gielk** [comment]
There is an app right ? there is no public api available to connect tot the klikaanklikuit system ?

**Comment by robertklep** [comment]
This project is based on a (DIY) hardware solution, where you have a Raspberry Pi that controls (through a small transmitter module) your KaKu devices. It doesn't use an API, or an app, or the KaKu controller device.

**Comment by gielk** [comment]
Oke want ik ben op internet tegen gekomen dat ze ook aan te sturen zijn via een https link, ook zag ik dat https://triggi.com klikaanklikuit ondersteund.

**Comment by robertklep** [comment]
Ik denk dat je daar het [Internet Control Station](https://www.klikaanklikuit.nl/nl/ics-2000-internet-control-station.html) voor nodig hebt.

**Comment by gielk** [comment]
Oooooh nu zie ik het. Dankje
