### ISSUE TITLE
KlikAanKlikUit inbouw schakelaar

### ISSUE THREAD

**Issue by FredrickFloor** [robertklep/homebridge-klikaanklikuit#8]
Hi,

Supervet deze plugin! Al redelijk snel aan de praat, maar nog niet met mijn INBOUW SCHAKELAAR AWMR-300. Dit valt onder de 'type' : 'switch' toch?

De 'outlet' werkte bijna direct, maar de 'switch' krijg ik nog niet zo aan de praat.

**Comment by kevinriemens** [comment]
Hey,

In pricipe moet de switch gewoon werken. Ik gebruik zelf ook een aantal inbouw schakelaars. Je moet alleen even opletten of je schakelaars zelf leren zijn of niet, maar wel ook zo zijn 'ingeleerd'. Als je bijv. een zelflereren inbouwschakelaar hebt, maar de afstandsbediening is nog 'oude stijl', dan kun je twee dingen doen:

Of ik de config.json oldStyle: true bij het accessoire erbij zetten (net zoals dimmable: true), dan gebruikt hij het DIP commando ipv LEARN commando. Wat je ook kan doen (mits je device learnable is) is het device een nieuwe code aan laten leren.
Bijv:
Voeg een homekit accessoire toe op een code die nog nergens anders aan assigned is, start homebridge opnieuw met je nieuwe accessoire. Zet vervolgens je schakelaar op 'leer' modus en je zult zien dat de schakelaar dit signaal gewoon ontvangt van de lightmanager en vanaf dan 'aangeleerd' is. Daarna kun je hem gewoon gebruiken.

**Comment by kevinriemens** [comment]
Het type maakt volgens mij niet zo veel uit. Uiteindelijk komt het allemaal op 'On' of 'Off' neer voor zo ver ik kan zien in de code. Wat belangrijker is, denk ik, is dat je het 'dimmable: true' weghaalt uit de config voor die lamp. Die gebruikt namelijk het 'dim' commando uit de driver.

Het type is namelijk volgens mij alleen maar om het icoontje in Homekit weer te geven. Volgens mij heeft dat voor de rest geen functie.

**Comment by robertklep** [comment]
Klopt, het type maakt niet zoveel uit.

Waar je wel even op moet letten is dat je in de config het juiste JSON type meegeeft aan  `address`: voor de nieuwe(re) KaKu devices moet dat een nummer zijn (tenzij je het device een code van een oude KaKu remote hebt laten leren).

Dus niet dit:

```
{
  "name"    : "Inbouwswitch",
  "type"    : "Switch",
  "address" : "0",
   device"  : "0"
}
```

Maar dit:

```
{
  "name"    : "Inbouwswitch",
  "type"    : "Switch",
  "address" : 0,
   device"  : 0
}
```

(zonder quotes om de getallen heen)

Ik zal vandaag of morgen de plugin aanpassen zodat het automatisch goed werkt bij waarden die eruit zien als een nummer.

**Comment by FredrickFloor** [comment]
Ah dat was hem inderdaad! Had het verschil in wel of niet quotes niet gezien!

Werkt super!

**Comment by pjansen75** [comment]
Misschien een stomme vraag, maar...
Hoe kom ik aan het nummer van "address" en "device"?
Alvast bedankt.

**Comment by robertklep** [comment]
@pjansen75 

De "oude" devices hadden een simpele draaiknop waarmee je die waarden kon instellen, voor nieuwe (zelflerende) devices bedenk ik zelf een stel waarden en laat het device die code leren.

Een simpele manier om dat te doen is via mijn [`kaku-rpi`](https://github.com/robertklep/node-kaku-rpi) package:
```
$ npm install kaku-rpi
$ ./node_modules/.bin/kaku PIN ADRES DEVICE 1
```

**Comment by pjansen75** [comment]
Helaas gaat dit me dan net weer wat te snel.
Ik lijk wat stappen te missen om dat dan voor elkaar te kunnen krijgen.
Ik neem aan, dat je dit niet helemaal uitgewerkt digitaal hebt?
Ik heb je package kaku-rpi al geïnstalleerd, maar ik weet niet hoe en wat verder met 433MHzForArduino project.

**Comment by robertklep** [comment]
@pjansen75 waar het mee begint is dat je een Raspberry Pi hebt met daaraan gekoppeld een 433Mhz zendermodule (helaas is de pagina waarnaar ik verwijs in de README offline op het moment, maar [hier](https://hackernoon.com/diy-home-automation-fan-control-with-raspberry-pi-3-rf-transmitter-and-homebridge-59ad24845770#1aef) staat het aansluitschema; je hebt alleen een zender nodig, dat is de module rechts; de ontvanger, links, wordt niet gebruikt voor dit project).

Dat staat los van het 433MHzForArduino project (dat gaat over andere hardware en andere software).

**Comment by pjansen75** [comment]
Ok, die zendermodule heb ik en deze is aangesloten op pin 11.

**Comment by robertklep** [comment]
@pjansen75 okay, dan moet je een KaKu device in leesmodus zetten en het volgende uitvoeren:
```
./node_modules/.bin/kaku 11 M 1 1
```

Daarmee stuur je, via pin 11, het "AAN" command (dat is de laatste 1, als het een 0 is, dan stuurt 'ie het "UIT" commando) naar device "M" adres 1.

Als het goed is, dan zal het device die code moeten leren. Vervolgens kun je een paar keer met hetzelfde commando AAN/UIT/AAN/UIT... sturen, om te kijken of het ook echt werkt.

Zo niet, dan kun je ook de "new-style" adressering proberen. Daarbij is de deviceID geen letter, maar een cijfer. Het adres is altijd een cijfer.

Bijvoorbeeld:
```
./node_modules/.bin/kaku 11 1234 1 1
```

De deviceID is dan `1234` geworden. Dat heeft dan wel weer consequenties voor je config file, want in plaats van dit:

```
"device" : "M"
```

Moet het dit zijn:
```
"device" : 1234
```

(dus "old-style" zijn letters en moeten tussen aanhalingstekens staan in de Homebridge config, "new-style" zijn nummers en daar mogen geen aanhalingstekens omheen staan)

**Comment by pjansen75** [comment]
Robert, heeeeeeel erg bedankt!
Het werkt!! Hier ben ik echt heeeeel blij mee.
Hopelijk mag ik nog één vraag je stellen.
Mijn config bestand ziet er nu zo uit:
`{
	"bridge": {
		"name": "Homebridge",
		"username": "CC:21:3E:E4:DE:33",
		"port": 51826,
		"pin": "031-45-154"
	},
	"platforms": [{
		"platform": "KlikAanKlikUit",
		"driver": {
			"type": "rpi",
			"pin": 11
		},
		"accessories": [{
				"name": "Spotjes zolderkamer",
				"type": "Lightbulb",
				"dimmable": false,
				"address": "M",
				"device": 1
			},
			{
				"name": "LED lamp",
				"type": "Lightbulb",
				"dimmable": true,
				"address": 5201,
				"device": 2
			}
		]

	}]
}`
Hoe kan ik hier dan een nieuw platform aan toevoegen, zoals bijvoorbeeld:
`"platforms": [{
    "platform": "Orvibo"
}],
`

Gr. Pieter

**Comment by robertklep** [comment]
@pjansen75 dat wordt dan zoiets:
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:21:3E:E4:DE:33",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "KlikAanKlikUit",
      "driver": {
        "type": "rpi",
        "pin": 11
      },
      "accessories": [
        {
          "name": "Spotjes zolderkamer",
          "type": "Lightbulb",
          "dimmable": false,
          "address": "M",
          "device": 1
        },
        {
          "name": "LED lamp",
          "type": "Lightbulb",
          "dimmable": true,
          "address": 5201,
          "device": 2
        }
      ]
    },
    {
      "platform": "Orvibo"
    }
  ]
}
```

**Comment by pjansen75** [comment]
Super!!

**Comment by pjansen75** [comment]
Ik hoop, dat ik je nog een vraag mag stellen.
Ik heb nu deze config:

> {
 "bridge": {
 "name": "Homebridge",
 "username": "CC:21:3E:E4:DE:33",
 "port": 51826,
 "pin": "031-45-154"
 },
 "platforms": [{
 "platform": "KlikAanKlikUit",
 "driver": {
 "type": "rpi",
 "pin": 11
 },
 "accessories": [{
 "name": "Spotjes zolderkamer",
 "type": "Lightbulb",
 "dimmable": false,
 "address": "M",
 "device": 1
 },
 {
 "name": "LED lamp",
 "type": "Lightbulb",
 "dimmable": true,
 "address": 5201,
 "device": 2
 },
 {
 "name": "LEDstrip keuken",
 "type": "Lightbulb",
 "dimmable": true,
 "address": 5202,
 "device": 3
 }
 ]
 }
 ]
 }

> 
Nu wil ik daar nog een accessoire aan toevoegen, namelijk:

> "accessories": [
 {
 "accessory": "MagicHome",
 "name": "LED Strip",
 "ip": "192.168.1.111",
 "setup": "RGBWW",
 "purewhite": false
 }
 ]

> 
Afzonderlijk van elkaar krijg ik het welk werkend, maar als ik de scripts samenvoeg, dan klapt homebridge eruit en werkt het dus niet meer. Wat doe ik fout?
Alvast bedankt.

**Comment by robertklep** [comment]
@pjansen75 probeer dit eens:
```
{
  "bridge": {
    "name": "Homebridge",
    "username": "CC:21:3E:E4:DE:33",
    "port": 51826,
    "pin": "031-45-154"
  },
  "platforms": [
    {
      "platform": "KlikAanKlikUit",
      "driver": {
        "type": "rpi",
        "pin": 11
      },
      "accessories": [
        {
          "name": "Spotjes zolderkamer",
          "type": "Lightbulb",
          "dimmable": false,
          "address": "M",
          "device": 1
        },
        {
          "name": "LED lamp",
          "type": "Lightbulb",
          "dimmable": true,
          "address": 5201,
          "device": 2
        },
        {
          "name": "LEDstrip keuken",
          "type": "Lightbulb",
          "dimmable": true,
          "address": 5202,
          "device": 3
        }
      ]
    }
  ],
  "accessories": [
    {
      "accessory": "MagicHome",
      "name": "LED Strip",
      "ip": "192.168.1.111",
      "setup": "RGBWW",
      "purewhite": false
    }
  ]
}
```

Je hebt "platforms" en "accessories", maar het lastige daarbij is dat een platform ook weer "accessories" kan hebben, alleen horen die bij dat specifieke platform. Als je daar een willekeurige andere accessory aan toevoegd snapt het platform dat niet en kan de zaak dus crashen.

**Comment by pjansen75** [comment]
Geweldig!! Het werkt! Dankjewel,
